export const DINING_HALLS = [
  {
    id: 'de-neve',
    name: '[De Neve Dining Hall]',
    emoji: '🏛️',
    color: 'bg-pastel-peach',
    items: [
      { id: 'dn-1', name: '[Grilled Salmon]',       rating: '[8.4]', category: '[Entree]',  dietary: '[GF]' },
      { id: 'dn-2', name: '[Pasta Primavera]',      rating: '[7.2]', category: '[Entree]',  dietary: '[V]'  },
      { id: 'dn-3', name: '[Caesar Salad]',         rating: '[6.8]', category: '[Salad]',   dietary: '[V]'  },
      { id: 'dn-4', name: '[Chocolate Lava Cake]',  rating: '[9.1]', category: '[Dessert]', dietary: '[]'   },
    ],
  },
  {
    id: 'epicuria',
    name: '[Epicuria at Covel]',
    emoji: '🌿',
    color: 'bg-pastel-sage',
    items: [
      { id: 'ep-1', name: '[Mediterranean Bowl]',  rating: '[8.9]', category: '[Entree]', dietary: '[VG]' },
      { id: 'ep-2', name: '[Wood-fired Pizza]',    rating: '[8.0]', category: '[Entree]', dietary: '[V]'  },
      { id: 'ep-3', name: '[Roasted Vegetables]',  rating: '[6.5]', category: '[Side]',   dietary: '[VG]' },
    ],
  },
  {
    id: 'bruin-plate',
    name: '[Bruin Plate]',
    emoji: '🥦',
    color: 'bg-pastel-mint',
    items: [
      { id: 'bp-1', name: '[Acai Power Bowl]',   rating: '[9.3]', category: '[Entree]', dietary: '[VG]' },
      { id: 'bp-2', name: '[Quinoa Grain Bowl]', rating: '[7.7]', category: '[Entree]', dietary: '[VG]' },
      { id: 'bp-3', name: '[Green Smoothie]',    rating: '[7.0]', category: '[Drink]',  dietary: '[VG]' },
    ],
  },
  {
    id: 'feast',
    name: '[Feast at Rieber]',
    emoji: '🍜',
    color: 'bg-pastel-lemon',
    items: [
      { id: 'fe-1', name: '[Ramen Bowl]',        rating: '[8.6]', category: '[Entree]', dietary: '[]' },
      { id: 'fe-2', name: '[Kung Pao Chicken]',  rating: '[7.9]', category: '[Entree]', dietary: '[]' },
    ],
  },
]

export const FEED_POSTS = [
  {
    id: 'post-1',
    username:    '[bruin_foodie]',
    avatar:      'BF',
    avatarColor: 'bg-pastel-rose',
    itemName:    '[Grilled Salmon]',
    restaurant:  '[De Neve Dining Hall]',
    rating:      '[8.4]',
    comment:     '[The salmon was perfectly cooked today - crispy on the outside and incredibly tender inside. Highly recommend going before 6pm!]',
    date:        '[Today, 5:42 PM]',
    likes:       '[24]',
  },
  {
    id: 'post-2',
    username:    '[hungry_bruin]',
    avatar:      'HB',
    avatarColor: 'bg-pastel-sky',
    itemName:    '[Acai Power Bowl]',
    restaurant:  '[Bruin Plate]',
    rating:      '[9.3]',
    comment:     '[Best thing I have had on The Hill all quarter. The granola is fresh and the acai is not overly sweet. 10/10 would recommend.]',
    date:        '[Yesterday, 12:15 PM]',
    likes:       '[41]',
  },
  {
    id: 'post-3',
    username:    '[ucla_eats_2025]',
    avatar:      'UE',
    avatarColor: 'bg-pastel-lavender',
    itemName:    '[Mediterranean Bowl]',
    restaurant:  '[Epicuria at Covel]',
    rating:      '[8.9]',
    comment:     '[Epicuria never misses. The hummus was freshly made and the pita was warm. Worth the trek to Covel.]',
    date:        '[2 days ago]',
    likes:       '[17]',
  },
  {
    id: 'post-4',
    username:    '[westwood_wanderer]',
    avatar:      'WW',
    avatarColor: 'bg-pastel-peach',
    itemName:    '[Chocolate Lava Cake]',
    restaurant:  '[De Neve Dining Hall]',
    rating:      '[9.1]',
    comment:     '[I dream about this dessert. Perfectly molten center every single time. De Neve pastry team deserves a raise.]',
    date:        '[3 days ago]',
    likes:       '[58]',
  },
  {
    id: 'post-5',
    username:    '[hill_life_305]',
    avatar:      'HL',
    avatarColor: 'bg-pastel-mint',
    itemName:    '[Ramen Bowl]',
    restaurant:  '[Feast at Rieber]',
    rating:      '[8.6]',
    comment:     '[Feast really stepped up their ramen game. Rich broth, chewy noodles, perfect soft-boiled egg. Go early - it runs out!]',
    date:        '[4 days ago]',
    likes:       '[33]',
  },
]

export const CALENDAR_DAYS = [
  { day: 'Mon', date: '[Mar 3]', restaurant: '[De Neve Dining Hall]',  meal: '[Grilled Salmon Night]',     why: '[Highest-rated protein this week based on 47 Bruin reviews. Peak freshness on Mondays.]',         emoji: '🐟' },
  { day: 'Tue', date: '[Mar 4]', restaurant: '[Bruin Plate]',          meal: '[Acai Bowl Morning]',         why: '[Most-liked breakfast item this month. Community says portions are extra generous on Tuesdays.]', emoji: '🫐' },
  { day: 'Wed', date: '[Mar 5]', restaurant: '[Epicuria at Covel]',    meal: '[Mediterranean Wednesday]',   why: '[Epicurias weekly Mediterranean menu drops Wednesdays. Rated 9.2 avg by repeat visitors.]',        emoji: '🌿' },
  { day: 'Thu', date: '[Mar 6]', restaurant: '[Feast at Rieber]',      meal: '[Ramen Bowl Special]',        why: '[Feast serves their signature broth recipe Thursdays only. 89% positive sentiment this quarter.]', emoji: '🍜' },
  { day: 'Fri', date: '[Mar 7]', restaurant: '[De Neve Dining Hall]',  meal: '[Friday Pizza Night]',        why: '[Wood-fired pizza is a Friday tradition. Lines move fast and ratings peak at 8.7 on Fridays.]',    emoji: '🍕' },
  { day: 'Sat', date: '[Mar 8]', restaurant: '[Bruin Plate]',          meal: '[Weekend Brunch Spread]',     why: '[Weekend brunch gets extra budget. Community top pick for relaxed Saturday mornings on The Hill.]', emoji: '☀️' },
  { day: 'Sun', date: '[Mar 9]', restaurant: '[Epicuria at Covel]',    meal: '[Sunday Comfort Dinner]',     why: '[Epicurias Sunday roast scores highest weekly. Perfect comfort food before the week starts.]',      emoji: '🍗' },
]

export const TRENDING_ITEM = {
  name:       '[Acai Power Bowl]',
  restaurant: '[Bruin Plate]',
  rating:     '[9.3]',
  reviews:    '[127]',
  summary:    '[Bruins are obsessed this week - the granola is freshly made and the fruit portions are massive. Most reviewers say it is the best breakfast option on The Hill right now.]',
  emoji:      '🫐',
  tag:        '[#1 Today]',
}
